'use strict';
let data, benchmarkId='libero', trackId='p1-2ep', view='leaderboard', ascending=false;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=(s,n)=>n>0&&s!==null&&s!==undefined?`${(100*s/n).toFixed(1)}%`:'—';
const num=n=>Number(n||0).toLocaleString('en-US');
const suiteName=s=>({libero_spatial:'Spatial',libero_object:'Object',libero_goal:'Goal',libero_10:'Long-horizon'}[s]||s||'诊断任务');
const bench=()=>data.benchmarks.find(b=>b.id===benchmarkId)||data.benchmarks[0];
const track=()=>bench().tracks.find(t=>t.id===trackId)||bench().tracks[0];
const statusLabel=r=>({complete:'已核验',training_running:'训练中',training:'训练中',training_incomplete:'训练未完成',awaiting_evaluation:'待评估',waiting_gpu:'等待GPU',waiting_cache_or_dependency:'等待缓存',waiting_cache:'等待缓存',pending:'待评估',in_progress:'评估中',partial:'评估中',running:'评估中',blocked:'访问受阻'}[r.progressStatus||r.status]||r.progressStatus||r.status||'待评估');
const safeUrl=u=>/^(https?:\/\/|data\/media\/)/.test(u||'')?u:'#';
// Encoder identity is stable across heads, filters, benchmarks and result order.
const encoderIdentity={
  resnet50_in1k_v2:['R50','#647267'], vitb16_in1k_v1:['ViT','#967843'],
  mae_b16:['MAE','#89784a'], dinov2_b14_reg:['D2B','#5c8294'],
  dinov3_b16:['D3B','#526fa5'], dinov3_l16:['D3L','#7273a4'],
  clip_b16:['CLP','#98726b'], siglip2_b16_224:['S2B','#b07969'],
  siglip2_so400m14_384:['S2S','#9d5e68'], eupe_vit_b:['EUV','#548375'],
  eupe_convnext_b:['EUC','#759054'], vc1_b:['VCB','#927a91'],
  vc1_l:['VCL','#a36f8b'], pe_spatial_b16_512:['PES','#568b9c'],
  pe_core_b16_224:['PEC','#697faf'], r3m_resnet50:['R3M','#a07d53'],
  vip:['VIP','#8b8850'], theia_b_cdiv:['THB','#7489a0'],
  sam21_hiera_t:['SAM','#739879'], dav2_b:['DA2','#ab954c'],
  c_radio_v3_b:['CR3','#8c74a3'], c_radio_v4_so400m:['CR4','#a177a0']
};
const encoderStyle=id=>`--encoder-color:${(encoderIdentity[id]||['?', '#647267'])[1]}`;
function encoderLabel(r,showId=false){const identity=encoderIdentity[r.encoder]||['?', '#647267'];return `<span class="encoder-identity" style="${encoderStyle(r.encoder)}"><span class="encoder-mark" aria-hidden="true">${identity[0]}</span><span class="encoder-name">${esc(r.encoderLabel||r.encoder)}${r.server?` · ${esc(r.server)}`:''}${showId?`<small>${esc(r.encoder)}</small>`:''}</span></span>`;}
function logDate(value){const date=new Date(value);return Number.isNaN(date.getTime())?'时间未记录':date.toISOString().replace('T',' ').slice(0,16)+' UTC';}
function badge(head){return `<span class="head-badge ${String(head).toLowerCase()==='dp'?'dp':''}">${esc(String(head||'—').toUpperCase())}</span>`;}
function metric(label,value,note,suffix=''){return `<div class="metric"><div class="metric-label">${label}</div><div class="metric-value">${value}<small>${suffix}</small></div><div class="metric-note">${note}</div></div>`;}
function visibleTasks(){const s=$('#suite').value,q=$('#search').value.trim().toLowerCase();return (bench().tasks||[]).filter(t=>(s==='all'||t.suite===s)&&(!q||`${t.name} ${t.instruction} ${t.suite}`.toLowerCase().includes(q)));}
function runScore(r,suite=$('#suite').value){if(suite==='all')return {successes:r.successes,episodes:r.episodes||0};const ids=new Set(bench().tasks.filter(t=>t.suite===suite).map(t=>t.id));const a=(r.taskResults||[]).filter(t=>ids.has(t.taskId)&&t.episodes>0);return {successes:(r.policyFamily==='act_native_7'&&r.status!=='complete')||a.some(t=>typeof t.successes!=='number')?null:a.reduce((n,t)=>n+t.successes,0),episodes:a.reduce((n,t)=>n+t.episodes,0)};}
function visibleRuns(ignoreSearch=false){const h=$('#head').value,q=ignoreSearch?'':$('#search').value.trim().toLowerCase();return (track()?.runs||[]).filter(r=>(h==='all'||r.head?.toUpperCase()===h)&&(!q||`${r.encoder} ${r.encoderLabel} ${r.head}`.toLowerCase().includes(q))).sort((a,b)=>{if(a.rankingEligible!==b.rankingEligible)return a.rankingEligible?-1:1;if(!track()?.ranked)return (a.encoderLabel||a.encoder).localeCompare(b.encoderLabel||b.encoder);const x=runScore(a),y=runScore(b);return (ascending?1:-1)*((x.episodes?x.successes/x.episodes:-1)-(y.episodes?y.successes/y.episodes:-1));});}
function render(){const b=bench(),t=track(),isLog=view==='log';$('#breadcrumb').textContent=isLog?'全局实验日志':b.name;$('#page-title').textContent=isLog?'实验日志':b.id==='libero'?'LIBERO, in focus.':`${b.name}, in focus.`;$('#description').textContent=isLog?'跨 benchmark 的实验进展、协议变化与证据记录；代码提交单独列示，只关联明确提供的提交。':b.description;$('#source').href=safeUrl(isLog?data.repository?.commitsUrl:b.sourceUrl);$('#source').textContent=isLog?'GitHub 提交记录 ↗':'官方项目 ↗';$('#source').hidden=isLog?!data.repository?.commitsUrl:!b.sourceUrl;
$('#metrics').hidden=isLog;$('.controls').hidden=isLog;const repo=$('#repository-link');if(data.repository?.url)repo.href=safeUrl(data.repository.url);repo.textContent=`GitHub · ${data.repository?.isPrivate===false?'公开':'私有'}仓库 ↗`;
$('#bench-count').textContent=String(data.benchmarks.length).padStart(2,'0');$('#benchmarks').innerHTML=data.benchmarks.map(x=>`<button class="bench ${!isLog&&x.id===b.id?'active':''}" data-benchmark="${esc(x.id)}" ${!isLog&&x.id===b.id?'aria-current="page"':''}><span class="bench-name">${esc(x.name)}<small>${x.id==='libero'?'多任务 · 视觉编码器评测':x.status==='planned'?'后续研究 · 尚未接入':x.status==='evaluated'?'有实测数据':'独立鲁棒性诊断'}</small></span><span class="bench-count">${x.status==='planned'?'—':x.taskCount??'↗'}</span></button>`).join('');
$('#track').innerHTML=(b.tracks||[]).map(x=>`<option value="${esc(x.id)}" ${x.id===t?.id?'selected':''}>${esc(x.label)}</option>`).join('')||'<option>暂无评估</option>';$('#track').disabled=!t;
const rs=t?.runs||[],done=rs.filter(r=>r.rankingEligible),samples=rs.reduce((n,r)=>n+(r.episodes||0),0),enc=new Set(rs.map(r=>r.encoder));
$('#metrics').innerHTML=metric('任务覆盖',b.taskCount??'—',b.taskCountLabel||`${(b.tasks||[]).length} 个已登记任务`)+metric('视觉编码器',enc.size||'—',rs.length?`${rs.length} 个编码器 × 动作头组合`:'尚无模型评估')+metric(t?.ranked?'完整评估组合':'已核验回合',t?.ranked?done.length:num(samples),t?.ranked?'未完成组合不计失败':'局部覆盖，不进入完整排行榜',t?.ranked?`/ ${rs.length}`:'')+metric('每模型 / 每任务',t?.targetEpisodesPerTask??'—',`训练种子：${t?.trainingSeeds?.join(' / ')||'未开始'}`,'回合');
$('#stage').textContent=isLog?'全局记录':t?.id==='native-20x1'?'原生开发 · 20k':t?.id==='expanded-20x3'?(b.tracks.some(x=>x.id==='native-20x1')?'历史开发 · 20×3':'扩展评估 · 累积中'):t?'开发数据 · 非正式排名':'计划阶段';
document.querySelectorAll('[data-view]').forEach(e=>{e.classList.toggle('active',e.dataset.view===view);e.setAttribute('aria-current',e.dataset.view===view?'page':'false');});
const old=$('#suite').value;$('#suite').innerHTML='<option value="all">全部任务集</option>'+[...new Set((b.tasks||[]).map(x=>x.suite))].map(s=>`<option value="${esc(s)}">${esc(suiteName(s))}</option>`).join('');if([...$('#suite').options].some(o=>o.value===old))$('#suite').value=old;
$('#head').disabled=view==='protocol';$('#suite').disabled=view==='protocol'||(view==='leaderboard'&&!t?.runs?.some(r=>r.taskResults?.length));if($('#suite').disabled)$('#suite').value='all';$('#search').disabled=view==='protocol';
renderContent();}
function empty(title,message){return `<div class="empty-state"><div class="eyebrow">EVIDENCE FIRST</div><h2>${esc(title)}</h2><p>${esc(message)}</p>${bench().sourceUrl?`<a href="${esc(safeUrl(bench().sourceUrl))}" target="_blank" rel="noopener">了解官方 benchmark ↗</a>`:''}</div>`;}
function notice(){const t=track();return `<div class="notice"><strong>${t?.ranked?'开发快照':'覆盖说明'}</strong><span>${t?.ranked?'同一评估版本内比较成功率；当前为训练 seed17、每任务2回合，不能作为最终排名。':t?.id==='native-20x1'?'保留原生空间tokens，完整batch32训练20000步；每任务20个评估种子各1回合。收齐800回合才显示单训练seed开发成绩，待三训练seed汇总，不作正式排名。历史P1与20×3分母独立。':t?.id==='expanded-20x3'?`${bench().tracks.some(x=>x.id==='native-20x1')?'旧协议已停止新增，保留历史审计快照。':''}目标：20个评估种子 × 每种子3回合 / 任务。以下仅展示已核验进度，覆盖未齐，不排序、不与旧2回合成绩合并。`:'以下为独立任务诊断；任务、扰动或初态覆盖不齐，不能作为该 benchmark 的整体成功率。'}${t?.id==='native-20x1'&&t.servers?.length?` 审计快照：${t.servers.map(s=>`${esc(s.id)} ${esc(logDate(s.observedAt))}`).join('；')}。`:''}</span></div>`;}
function scoreHTML(s,n){return n>0&&s!==null&&s!==undefined?`<div class="score"><strong>${pct(s,n)}</strong><span class="bar"><i style="width:${100*s/n}%"></i></span></div>`:`<div class="score"><span class="null">${track()?.id==='native-20x1'?'—':n?'覆盖未齐':'尚无结果'}</span></div>`;}
function renderContent(){stopGifs();const b=bench(),t=track();if(view==='log')$('#content').innerHTML=experimentLog();else if(view==='protocol')$('#content').innerHTML=protocol();else if(view==='tasks')renderTasks();else if(!t||!t.runs?.length)$('#content').innerHTML=empty('这里的实验尚未开始',b.status==='planned'?'已纳入研究视野，尚未接入任务与评测数据。':'当前没有可展示的模型成绩。任务页可查看已审计的素材与诊断条件。');else{const runs=visibleRuns();const suites=[...new Set(b.tasks.map(x=>x.suite))];const suiteCols=b.id==='libero'&&t.id==='p1-2ep';let rank=0;let lastRate=null;
$('#content').innerHTML=notice()+`<div class="table-wrap"><table><thead><tr><th>#</th><th>视觉编码器</th><th>动作模型</th><th><button class="sort-button" id="sort" ${!t.ranked?'disabled':''}>成功率 ${t.ranked?(ascending?'↑':'↓'):''}</button></th><th>成功 / 有效</th>${suiteCols?suites.map(s=>`<th class="suite-col">${suiteName(s)}</th>`).join(''):''}<th class="status-col">评估状态</th><th></th></tr></thead><tbody>${runs.map((r,index)=>{const a=runScore(r);const rate=a.episodes?a.successes/a.episodes:null;rank=1+visibleRuns(true).filter(x=>x.rankingEligible&&runScore(x).episodes>0&&runScore(x).successes/runScore(x).episodes>rate).length;return `<tr><td class="rank ${rank===1?'first':''}">${t.ranked&&r.rankingEligible?String(rank).padStart(2,'0'):'—'}</td><td><button class="link-button encoder" data-run="${esc(r.id)}">${encoderLabel(r,true)}</button></td><td>${badge(r.head)}</td><td>${scoreHTML(a.successes,a.episodes)}</td><td class="sample">${a.episodes?`${a.successes??'—'} / ${num(a.episodes)}`:'—'}</td>${suiteCols?suites.map(s=>{const z=runScore(r,s);return `<td class="suite-col suite-score">${pct(z.successes,z.episodes)}</td>`}).join(''):''}<td class="status-col"><span class="status ${r.rankingEligible?'complete':'pending'}">${esc(statusLabel(r))}${!t.ranked&&r.expectedEpisodes?` · ${num(r.episodes)}/${num(r.expectedEpisodes)}`:''}</span></td><td><button class="link-button" data-run="${esc(r.id)}" aria-label="查看${esc(r.encoderLabel||r.encoder)}详情">↗</button></td></tr>`;}).join('')||'<tr><td colspan="11">没有符合筛选条件的模型。</td></tr>'}</tbody></table></div><div class="table-caption"><span>${runs.length} 个组合 · 点击编码器查看逐任务表现</span><span>分母为有效回合；缺失结果保留为空</span></div>`;}}
function mediaPreview(task,index){const m=(task.media||[]).find(x=>x.type==='gif'&&x.runId)||(task.media||[]).find(x=>x.type==='gif')||task.media?.[0];const poster=m?.posterUrl||(m?.type==='image'?m.url:null);if(!m)return `<div class="empty-visual"><span class="task-num">${String(index+1).padStart(2,'0')}</span><span class="empty-label">执行 GIF 尚未收录</span></div>`;return `${poster?`<img src="${esc(safeUrl(poster))}" loading="lazy" alt="${esc(task.instruction)} · 实验场景">`:`<div class="empty-visual"><span class="task-num">${String(index+1).padStart(2,'0')}</span><span class="empty-label">真实执行片段</span></div>`}<span class="media-badge" title="${esc(m.label)}">${esc(m.type==='gif'?m.label:'真实场景 · 静态帧')}</span>${m.type==='gif'?`<button class="play-gif" data-gif="${esc(m.url)}" data-poster="${esc(poster||'')}" aria-pressed="false">▶ 播放 GIF</button>`:''}`;}
function renderTasks(){const tasks=visibleTasks();if(!tasks.length){$('#content').innerHTML=empty(bench().tasks.length?'没有匹配的任务':'任务素材尚未接入','已完成的评估与真实素材会在这里按任务整理。');return;}const t=track();$('#content').innerHTML=`<div class="table-caption"><span>${tasks.length} 个任务 · 真实场景与执行素材</span><span>GIF注明模型与来源；未录制的任务仅展示静态帧</span></div><div class="task-grid">${tasks.map((task,i)=>{const head=$('#head').value;const allowed=new Set((t?.runs||[]).filter(r=>head==='all'||r.head?.toUpperCase()===head).map(r=>r.id));const results=(task.results||[]).filter(r=>r.episodes>0&&allowed.has(r.runId));return `<article class="task-card"><div class="task-visual">${mediaPreview(task,i)}</div><div class="task-info"><div class="task-suite">${esc(suiteName(task.suite))} / ${esc(task.id)}</div><h2 class="task-title"><button class="link-button" data-task="${esc(task.id)}">${esc(task.instruction||task.name.replaceAll('_',' '))}</button></h2><div class="task-bottom"><span>${t?.id==='p1-2ep'?`${results.length} 个模型有结果`:'查看当前评估版本'}</span><button data-task="${esc(task.id)}">任务详情 ↗</button></div></div></article>`;}).join('')}</div>`;}
function protocol(){const t=track(),b=bench();return `<div class="protocol-grid"><article class="protocol-block"><h2>One protocol. Fair comparison.</h2><dl><dt>Benchmark</dt><dd>${esc(b.name)}</dd><dt>当前版本</dt><dd>${esc(t?.label||'尚无评估')}</dd><dt>独立训练种子</dt><dd>${esc(t?.trainingSeeds?.join(', ')||'—')} · 目标 17 / 29 / 43</dd><dt>每模型、每任务目标</dt><dd>${t?.targetEpisodesPerTask||'—'} 回合</dd><dt>证据更新时间</dt><dd>${esc(data.updatedAt)}</dd></dl></article><article class="protocol-block"><h2>Read the evidence.</h2>${t?.id==='native-20x1'?'<p>Joint40多任务共同训练，冻结视觉编码器并保留原生空间tokens；ACT使用真实7层解码器，完整batch32训练20000步。</p><p>每个训练seed模型、每任务20个评估种子，每种子1回合，分别使用20个不同官方初态；完整800回合才显示该训练seed的开发成绩。17 / 29 / 43三训练seed尚待汇总，不与历史P1或20×3合并，不作正式排名。</p>':'<p>当前LIBERO为Joint40共同训练，冻结视觉编码器，比较DP与ACT。P1为开发校准；排行榜仅在相同协议和完整覆盖内排序。</p><p>历史扩展评估为每个训练模型、每任务20个评估种子，每种子3回合。官方每任务50个唯一初态，60回合包含10次跨评估种子的初态复用；它们不是60个独立物理场景。</p>'}<p>Plus／PRO的少量诊断与基础LIBERO分开，不混合成鲁棒性排名。未完成结果不会填0，也不会被计为失败。</p><p>GIF是有明确来源的执行节选，可能来自专家重放或早期诊断。素材标签与当前表格成绩相互独立；选中的视频不代表平均表现。</p></article></div>`;}
function openRun(id){const r=track().runs.find(x=>x.id===id);if(!r)return;$('#detail-eyebrow').textContent=`MODEL DETAIL / ${track().label}`;const tr=new Map((r.taskResults||[]).map(x=>[x.taskId,x]));$('#detail-body').innerHTML=`<h2 class="model-title">${encoderLabel(r)} ${badge(r.head)}</h2><p class="detail-instruction">${esc(statusLabel(r))}${r.server?` · ${esc(r.server)}`:''} · 训练种子 ${r.trainingSeed??track().trainingSeeds.join(' / ')}</p><div class="detail-stat">${pct(r.successes,r.episodes)}<small>${r.successes??'—'} / ${num(r.episodes)} 有效回合</small></div>${!r.rankingEligible?`<div class="notice">${track().id==='native-20x1'?(r.status==='complete'?'已完成800回合的单训练seed开发评估；待17 / 29 / 43三训练seed汇总，不作正式排名。':'模型覆盖未齐，仅展示已核验进度，不计算总体成功率。'):'覆盖未齐，不用于正式排名或跨覆盖比较。'}</div>`:''}<h3>逐任务成功 / 有效回合</h3><div class="heatmap">${bench().tasks.map((task,i)=>{const a=tr.get(task.id),n=a?.episodes||0,f=n&&typeof a.successes==='number'?a.successes/n:null;return `<button data-task="${esc(task.id)}" style="background:${f===null?'#f1f2ed':f===0?'#f1e7e1':f===1?'#bbd1b8':'#dde7d6'}" title="${esc(task.instruction)}">${String(i+1).padStart(2,'0')}<small>${f!==null?`${a.successes}/${n}`:n?`${n}/${a.expectedEpisodes||'—'} 回合`:'—'}</small></button>`;}).join('')}</div>${r.groups?.length?`<h3>已审计评估种子组</h3><div class="table-wrap"><table><thead><tr><th>评估种子</th><th>有效 / 目标</th><th>组内成功数</th></tr></thead><tbody>${r.groups.map(g=>`<tr><td>${g.rootSeed}</td><td>${g.episodes} / ${g.expectedEpisodes}</td><td>${g.successes??'尚未收齐'}</td></tr>`).join('')}</tbody></table></div>`:''}<p class="dialog-note">${track().id==='native-20x1'?'每任务收齐20回合才显示该任务成功数；未收齐的格子只显示回合进度。历史素材按标签展示，不代表原生模型执行。':'点击格子查看任务、GIF与模型对比。空白格表示未评估；成功数为0表示已评估但未成功。'}</p>`;showDialog();}
function openTask(id){const task=bench().tasks.find(x=>x.id===id);if(!task)return;$('#detail-eyebrow').textContent=`TASK DETAIL / ${suiteName(task.suite)}`;const t=track(),rs=(t?.runs||[]).filter(r=>$('#head').value==='all'||r.head?.toUpperCase()===$('#head').value).map(r=>({r,a:r.taskResults?.find(x=>x.taskId===id)})).filter(x=>x.a?.episodes>0).sort((x,y)=>(typeof y.a.successes==='number'?y.a.successes/y.a.episodes:-1)-(typeof x.a.successes==='number'?x.a.successes/x.a.episodes:-1));const m=task.media?.find(x=>x.videoUrl&&x.runId)||task.media?.find(x=>x.videoUrl)||task.media?.find(x=>x.type==='video')||task.media?.[0];const v=m?.videoUrl||(m?.type==='video'?m.url:null);$('#detail-body').innerHTML=`<h2>${esc(task.instruction||task.name.replaceAll('_',' '))}</h2><p class="detail-instruction">${esc(task.id)} · ${esc(task.name)}</p>${v?`<video controls playsinline preload="metadata" ${m.posterUrl?`poster="${esc(safeUrl(m.posterUrl))}"`:''} src="${esc(safeUrl(v))}"></video>`:m?`<div class="task-visual" style="height:300px">${mediaPreview(task,0)}</div>`:'<div class="notice">该任务尚未收录执行GIF；下面保留真实评估数据。</div>'}${m?`<p class="media-caption">${esc(m.label)} · ${esc(typeof m.condition==='object'?JSON.stringify(m.condition):m.condition||'')} ${esc(m.previewLabel||m.playbackNote||m.note||'')}</p>`:''}<h3>该任务的模型表现</h3><p class="dialog-note">${esc(t?.label||'暂无评估')} ${t?.id==='native-20x1'?'· 单任务收齐20回合才显示成绩；未完整模型没有总体成功率':!t?.ranked?'· 覆盖可能不同，只作诊断':''}</p><div class="table-wrap"><table><thead><tr><th>编码器</th><th>动作模型</th><th>成功率</th><th>成功 / 有效</th></tr></thead><tbody>${rs.map(({r,a})=>`<tr><td><button class="link-button" data-run="${esc(r.id)}">${encoderLabel(r)}</button></td><td>${badge(r.head)}</td><td>${pct(a.successes,a.episodes)}</td><td class="sample">${a.successes??'—'} / ${a.episodes}</td></tr>`).join('')||'<tr><td colspan="4">当前版本没有该任务的逐回合结果。</td></tr>'}</tbody></table></div>`;showDialog();}
function experimentLog(){
  const entries=[...(data.experimentLog||[])].sort((a,b)=>(Date.parse(b.at)||0)-(Date.parse(a.at)||0));
  const types={evaluation:'评估记录',protocol:'协议更新',correction:'证据勘误',release:'版本发布'};
  const commits=data.repository?.recentCommits||[];
  return `<div class="log-intro"><div><h2>实验进展与证据</h2><p>${entries.length} 条已登记记录 · 数据快照 ${esc(logDate(data.updatedAt))}</p></div><span class="log-scope">所有 benchmark</span></div>
    <div class="log-layout"><section aria-label="实验记录">${entries.length?`<ol class="experiment-log">${entries.map(entry=>`<li id="log-${esc(entry.id)}"><article class="log-entry"><div class="log-meta"><time datetime="${esc(entry.at||'')}">${esc(logDate(entry.at))}</time><span class="log-type ${Object.hasOwn(types,entry.type)?esc(entry.type):'evaluation'}">${esc(types[entry.type]||entry.type||types.evaluation)}</span></div><h3>${esc(entry.title)}</h3><p>${esc(entry.summary)}</p><div class="log-evidence"><span>证据 · ${esc(entry.evidenceLabel||'尚未提供证据标签')}</span>${entry.commitUrl&&safeUrl(entry.commitUrl)!=='#'?`<a href="${esc(safeUrl(entry.commitUrl))}" target="_blank" rel="noopener">关联提交 ↗</a>`:'<span class="unlinked">未关联提交</span>'}</div></article></li>`).join('')}</ol>`:'<div class="empty-state"><h2>实验日志尚未收录</h2><p>后续记录将在核验后随数据快照发布。</p></div>'}</section>
    <aside class="commit-panel" aria-label="GitHub 代码提交"><h2>GitHub 提交</h2><p>实际代码历史，和左侧实验记录分别列示。${data.repository?.isPrivate!==false?'仓库为私有，访问需要相应权限。':''}</p>${commits.length?`<ol class="commit-list">${commits.map(commit=>`<li><time datetime="${esc(commit.at||'')}">${esc(logDate(commit.at))}</time><div>${commit.url&&safeUrl(commit.url)!=='#'?`<a href="${esc(safeUrl(commit.url))}" target="_blank" rel="noopener">${esc(commit.title)} ↗</a>`:esc(commit.title)}</div><code>${esc(String(commit.sha||'').slice(0,12))}</code></li>`).join('')}</ol>`:'<p class="commit-empty">当前快照尚未收录提交记录。</p>'}${data.repository?.commitsUrl?`<a class="all-commits" href="${esc(safeUrl(data.repository.commitsUrl))}" target="_blank" rel="noopener">查看完整提交历史 ↗</a>`:''}</aside></div>`;
}
function showDialog(){if(!$('#detail').open)$('#detail').showModal();$('#detail').scrollTop=0;}
function stopGifs(){document.querySelectorAll('[data-gif][aria-pressed="true"]').forEach(b=>{const p=b.closest('.task-visual');const im=p.querySelector('img');if(im){if(b.dataset.poster)im.src=b.dataset.poster;else im.remove();}b.setAttribute('aria-pressed','false');b.textContent='▶ 播放 GIF';});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-benchmark]');if(b){if(view==='log')view='leaderboard';benchmarkId=b.dataset.benchmark;trackId=bench().tracks[0]?.id;$('#search').value='';$('#suite').value='all';render();return;}const tab=e.target.closest('[data-view]');if(tab){view=tab.dataset.view;render();return;}const task=e.target.closest('[data-task]');if(task){openTask(task.dataset.task);return;}const run=e.target.closest('[data-run]');if(run){openRun(run.dataset.run);return;}const gif=e.target.closest('[data-gif]');if(gif){const was=gif.getAttribute('aria-pressed')==='true';stopGifs();if(!was){let im=gif.closest('.task-visual').querySelector('img');if(!im){im=document.createElement('img');im.alt='真实执行GIF';gif.closest('.task-visual').prepend(im);}im.src=safeUrl(gif.dataset.gif);gif.setAttribute('aria-pressed','true');gif.textContent='Ⅱ 暂停';}return;}if(e.target.closest('#sort')){ascending=!ascending;renderContent();}});
$('#track').addEventListener('change',e=>{trackId=e.target.value;render();});$('#head').addEventListener('change',renderContent);$('#suite').addEventListener('change',renderContent);$('#search').addEventListener('input',renderContent);$('#close-detail').onclick=()=>$('#detail').close();$('#detail').addEventListener('close',()=>{stopGifs();$('#detail-body').querySelectorAll('video').forEach(v=>v.pause());});$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))$('#detail').close();});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopGifs();document.querySelectorAll('video').forEach(v=>v.pause());}});const observer=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting&&e.target.getAttribute('aria-pressed')==='true')stopGifs();}));
async function load(){const button=$('#refresh');button.disabled=true;try{const response=await fetch('data/data.json',{cache:'no-store'});if(!response.ok)throw new Error(`数据读取失败 ${response.status}`);data=await response.json();if(!data.benchmarks?.length)throw new Error('没有可读取的benchmark数据');$('#update-time').textContent=`数据快照 · ${String(data.updatedAt).replace('T',' ').slice(0,16)} UTC`;$('#load-error').hidden=true;render();}catch(e){$('#load-error').hidden=false;$('#load-error').textContent=`暂时无法读取结果：${e.message}。请点击刷新重试；数据按已核验快照展示。`;}finally{button.disabled=false;}}
new MutationObserver(()=>document.querySelectorAll('[data-gif]').forEach(b=>observer.observe(b))).observe($('#content'),{childList:true,subtree:true});$('#refresh').onclick=load;load();
